Store.create!(name: 'Antofagasta', commune: 'Antofagasta', address: 'Balmaceda 2355 Mall Plaza', cluster: Cluster.find_by(name: 'C3'))
Store.create!(name: 'Calama', commune: 'Calama', address: 'Av. Balmaceda 3242', cluster: Cluster.find_by(name: 'C3'))
Store.create!(name: 'Copiapó', commune: 'Copiapó', address: 'Maipú 0110', cluster: Cluster.find_by(name: 'C3'))
Store.create!(name: 'La Serena', commune: 'La Serena', address: 'Alberto Solari 1400 Mall Plaza La Serena', cluster: Cluster.find_by(name: 'C3'))
Store.create!(name: 'Ovalle', commune: 'Ovalle', address: 'Prolongación Benavente 1075', cluster: Cluster.find_by(name: 'C3'))
Store.create!(name: 'La Calera', commune: 'La Calera', address: 'Prolongación J.J. Perez 12010', cluster: Cluster.find_by(name: 'C3'))
Store.create!(name: 'Quilpué', commune: 'Quilpué', address: 'Diego Portales 822', cluster: Cluster.find_by(name: 'C3'))
Store.create!(name: 'San Felipe', commune: 'San Felipe', address: "Av. Bernardo O'Higgins 1150", cluster: Cluster.find_by(name: 'C3'))
Store.create!(name: 'Valparaíso', commune: 'Valparaíso', address: 'Independencia 1806', cluster: Cluster.find_by(name: 'C3'))
Store.create!(name: 'Viña del Mar', commune: 'Viña del Mar', address: 'Sucre 250', cluster: Cluster.find_by(name: 'C3'))
Store.create!(name: 'Ahumada', commune: 'Santiago', address: 'Paseo Ahumada 25, 165, 280, 366', cluster: Cluster.find_by(name: 'C3'))
Store.create!(name: 'Alameda', commune: 'Santiago', address: 'Av. Libertador Bernardo O Higgins 3470', cluster: Cluster.find_by(name: 'C3'))
Store.create!(name: 'Alto Las Condes', commune: 'Las Condes', address: 'Av. Kennedy 9001, Local 1001', cluster: Cluster.find_by(name: 'ABC1'))
Store.create!(name: 'Arauco Maipú', commune: 'Maipú', address: 'Av. Américo Vespucio 399. Local 500', cluster: Cluster.find_by(name: 'C3'))
Store.create!(name: 'Costanera Center', commune: 'Providencia', address: 'Avenida Andrés Bello 2461', cluster: Cluster.find_by(name: 'C2'))
Store.create!(name: 'La Dehesa', commune: 'Lo Barnechea', address: 'La Dehesa 1445 local 1', cluster: Cluster.find_by(name: 'ABC1'))
Store.create!(name: 'Lyon', commune: 'Providencia', address: 'Avenida Providencia 2188', cluster: Cluster.find_by(name: 'C2'))
Store.create!(name: 'Manquehue', commune: 'Las Condes', address: 'Avenida Manquehue Sur N° 329', cluster: Cluster.find_by(name: 'ABC1'))
Store.create!(name: 'Melipilla', commune: 'Melipilla', address: 'Vargas 457', cluster: Cluster.find_by(name: 'C3'))
Store.create!(name: 'Parque Arauco', commune: 'Las Condes', address: 'Av. Presidente Kennedy 5413', cluster: Cluster.find_by(name: 'ABC1'))
Store.create!(name: 'Plaza Egaña', commune: 'La Reina', address: 'Larrain 5862', cluster: Cluster.find_by(name: 'C2'))
Store.create!(name: 'Plaza Norte', commune: 'Santiago', address: 'Av. Americo Vespucio 1737', cluster: Cluster.find_by(name: 'C3'))
Store.create!(name: 'Plaza Oeste', commune: 'Maipú', address: 'Av. Américo Vespucio 1501', cluster: Cluster.find_by(name: 'C3'))
Store.create!(name: 'Plaza Vespucio', commune: 'Santiago', address: 'Av. Vicuña Mackenna 7110', cluster: Cluster.find_by(name: 'C3'))
Store.create!(name: 'Puente', commune: 'Santiago', address: 'Puente 530', cluster: Cluster.find_by(name: 'C3'))
Store.create!(name: 'San Bernardo', commune: 'San Bernardo', address: 'Av. Jorge Alessandri 20040, Local 1', cluster: Cluster.find_by(name: 'C3'))
Store.create!(name: 'Tobalaba', commune: 'Puente Alto', address: 'Av. Camilo Henríquez 3296', cluster: Cluster.find_by(name: 'C3'))
Store.create!(name: 'Rancagua', commune: 'Rancagua', address: 'Sargento Cuevas 405', cluster: Cluster.find_by(name: 'C3'))
Store.create!(name: 'San Fernando', commune: 'San Fernando', address: 'Avenida Bernardo O´higgins 701', cluster: Cluster.find_by(name: 'C3'))
Store.create!(name: 'Curicó', commune: 'Curicó', address: 'Peña 615', cluster: Cluster.find_by(name: 'C3'))
Store.create!(name: 'Talca', commune: 'Talca', address: '1 Norte 1485', cluster: Cluster.find_by(name: 'C3'))
Store.create!(name: 'Chillán', commune: 'Chillán', address: 'El Roble 770, Local A', cluster: Cluster.find_by(name: 'C3'))
Store.create!(name: 'Concepción', commune: 'Concepción', address: 'Barros Arana 802', cluster: Cluster.find_by(name: 'C3'))
Store.create!(name: 'Plaza del Trébol', commune: 'Concepción', address: 'Av. José Alessandri 3177 Acceso Carriel Sur', cluster: Cluster.find_by(name: 'C3'))
Store.create!(name: 'Los Ángeles', commune: 'Los Ángeles', address: 'Valdivia 472', cluster: Cluster.find_by(name: 'C3'))
Store.create!(name: 'Pucón', commune: 'Pucón', address: 'Bernardo O`Higgins 112. Locales: 9, 10 y 11', cluster: Cluster.find_by(name: 'C3'))
Store.create!(name: 'Temuco', commune: 'Temuco', address: 'Arturo Prat 570', cluster: Cluster.find_by(name: 'C3'))
Store.create!(name: 'Valdivia', commune: 'Valdivia', address: 'Arauco 561', cluster: Cluster.find_by(name: 'C3'))
Store.create!(name: 'Castro', commune: 'Castro', address: 'Av. San Martin 457', cluster: Cluster.find_by(name: 'C3'))
Store.create!(name: 'Osorno', commune: 'Osorno', address: 'Eleuterio Ramírez 840', cluster: Cluster.find_by(name: 'C3'))
Store.create!(name: 'Puerto Montt', commune: 'Puerto Montt', address: 'Av. Juan Soler Manfredini 101', cluster: Cluster.find_by(name: 'C3'))
Store.create!(name: 'Punta Arenas', commune: 'Punta Arenas', address: 'Avenida Frei 01110', cluster: Cluster.find_by(name: 'C3'))

puts 'stores loaded'
