apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: kompose convert -o example.azure.deploy.yaml
      kompose.version: 1.18.0 ()
    creationTimestamp: null
    labels:
      io.kompose.service: app-tooxs
    name: app-tooxs
  spec:
    ports:
    - name: "80"
      port: 80
      targetPort: 80
    type: LoadBalancer
    selector:
      io.kompose.service: app-tooxs
  status:
    loadBalancer: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert -o example.azure.deploy.yaml
      kompose.version: 1.18.0 ()
    creationTimestamp: null
    labels:
      io.kompose.service: app-tooxs
    name: app-tooxs
  spec:
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: app-tooxs
      spec:
        containers:
        - env:
          - name: APP_HOST
            value: localhost
          - name: APP_PORT
            value: "80"
          - name: DEFAULT_URL_HOST
            value: localhost
          - name: SMTP_EMAIL_ADDRESS
            value: smtp.sendgrid.net
          - name: SMTP_EMAIL_AUTH
            value: plain
          - name: SMTP_EMAIL_DOMAIN
            value: tooxs.com
          - name: SMTP_EMAIL_PASSWORD
            value: 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
          - name: SMTP_EMAIL_PORT
            value: "587"
          - name: SMTP_EMAIL_STARTTLS
            value: "true"
          - name: SMTP_EMAIL_USERNAME
            value: apikey
          - name: TOOXS_DATABASE_HOST
            value: db-tooxs
          - name: TOOXS_DATABASE_NAME
            value: salesforce_reporter_development
          - name: TOOXS_DATABASE_PASSWORD
            value: dbtooxs_pass
          - name: TOOXS_DATABASE_PORT
            value: "5432"
          - name: TOOXS_DATABASE_USERNAME
            value: dbtooxs_user
          - name: TOOXS_REDIS_HOST
            value: redis-tooxs
          - name: TOOXS_REDIS_PORT
            value: "6379"
          - name: TOOXS_REDIS_SIDEQIK_HOST
            value: redis-sideqik-tooxs
          - name: TOOXS_REDIS_SIDEQIK_PORT
            value: "6380"
          image: cdgntooxs.azurecr.io/app-tooxs:local-demo
          name: app-tooxs
          ports:
          - containerPort: 80
          resources: {}
        restartPolicy: Always
  status: {}
kind: List
metadata: {}
