version: "3.3"

services:
  app-tooxs:
    tty: true
    stdin_open: true
    container_name: app-tooxs
    image: app-tooxs
    restart: unless-stopped
    links:
      - db-tooxs
      - redis-tooxs
      - redis-sidekiq-tooxs
    depends_on:
      - db-tooxs
      - redis-tooxs
      - redis-sidekiq-tooxs
    ports:
      - 3000:3000
    environment:
      APP_HOST: localhost
      APP_PORT: 3000

      # Desactivar Protección CSRF en API
      DIS_CSRF: OK

      TOOXS_DATABASE_HOST: db-tooxs
      TOOXS_DATABASE_PORT: 5432
      TOOXS_DATABASE_NAME: salco_salesforce_reporter_development
      TOOXS_DATABASE_USERNAME: dbtooxs_user
      TOOXS_DATABASE_PASSWORD: dbtooxs_pass

      TOOXS_REDIS_HOST: redis-tooxs
      TOOXS_REDIS_PORT: 6379
      # REDISTOGO_URL: 'redis://redistogo:32b0954968a03cde7d7455ee1f3ce11e@dory.redistogo.com:10732'

      TOOXS_REDIS_SIDEQIK_HOST: redis-sidekiq-tooxs
      TOOXS_REDIS_SIDEQIK_PORT: 6380
      # REDISTOGO_URL: 'redis://redistogo:32b0954968a03cde7d7455ee1f3ce11e@dory.redistogo.com:10732'

      DEFAULT_URL_HOST: localhost:3000
      SMTP_EMAIL_ADDRESS: smtp.sendgrid.net
      SMTP_EMAIL_PORT: 587
      SMTP_EMAIL_DOMAIN: tooxs.com
      SMTP_EMAIL_AUTH: plain
      SMTP_EMAIL_STARTTLS: 'true'
      SMTP_EMAIL_USERNAME: apikey
      SMTP_EMAIL_PASSWORD: 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

    volumes:
      - .:/var/app/tooxs

  db-tooxs:
    container_name: db-tooxs
    image: postgres:9.5.14
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: dbtooxs_user
      POSTGRES_PASSWORD: dbtooxs_pass
      PGDATA: /var/pg/data
    volumes:
      - ../local_db/pgdata:/var/pg/data
      - ../local_db/backups:/var/db_backups

  redis-tooxs:
    container_name: redis-tooxs
    image: redis:5
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - ../local_db/redis-data:/data

  redis-sidekiq-tooxs:
    container_name: redis-sidekiq-tooxs
    image: redis:5
    restart: unless-stopped
    ports:
      - 6380:6380
    volumes:
      - ../local_db/redis-sideqik-data:/data
    command: redis-server --port 6380

