defaults: &defaults

  start_dates:
    "2017-1": "2017-01-02"
    "2017-2": "2017-01-30"
    "2017-3": "2017-02-27"
    "2017-4": "2017-03-27"
    "2017-5": "2017-05-01"
    "2017-6": "2017-05-29"
    "2017-7": "2017-06-26"
    "2017-8": "2017-07-31"
    "2017-9": "2017-08-28"
    "2017-10": "2017-09-25"
    "2017-11": "2017-10-30"
    "2017-12": "2017-11-27"
    "2018-1": "2018-01-01"
    "2018-2": "2018-01-29"
    "2018-3": "2018-02-26"
    "2018-4": "2018-03-26"
    "2018-5": "2018-04-30"
    "2018-6": "2018-05-28"
    "2018-7": "2018-06-25"
    "2018-8": "2018-07-30"
    "2018-9": "2018-08-27"
    "2018-10": "2018-09-24"
    "2018-11": "2018-10-29"
    "2018-12": "2018-11-26"
    "2019-1": "2018-12-31"
    "2019-2": "2019-1-28"
    "2019-3": "2019-02-25"
    "2019-4": "2019-03-25"
    "2019-5": "2019-04-29"
    "2019-6": "2019-05-27"
    "2019-7": "2019-06-24"
    "2019-8": "2019-07-29"
    "2019-9": "2019-08-26"
    "2019-10": "2019-09-23"
    "2019-11": "2019-10-28"
    "2019-12": "2019-11-25"
    "2020-1": "2019-12-30"

  regions:
    i: "Región de Tarapacá"
    ii: "Región de Antofagasta"
    iii: "Región de Atacama"
    iv: "Región de Coquimbo"
    v: "Región de Valparaíso"
    vi: "Región del Libertador B. O'Higgins"
    vii: "Región del Maule"
    viii: "Región del Bíobío"
    ix: "Región de La Araucanía"
    x: "Región de Los Lagos"
    xi: "Región De Aisén del Gral. C. Ibáñez del Campo"
    xii: "Región de Magallanes y de La Antártica Chilena"
    xiii: "Región Metropolitana de Santiago"
    xiv: "Región de Los Ríos"
    xv: "Región de Arica y Parinacota"

  countries_groups:
    europe:
      va: "vatican city"
      ch: "switzerland"
      ad: "andorra"
      ee: "estonia"
      is: "iceland"
      am: "armenia"
      al: "albania"
      cz: "czech republic"
      ge: "georgia"
      at: "austria"
      ie: "ireland"
      gi: "gibraltar"
      gr: "greece"
      nl: "netherlands"
      pt: "portugal"
      'no': "norway"
      lv: "latvia"
      lt: "lithuania"
      lu: "luxembourg"
      es: "spain"
      it: "italy"
      ro: "romania"
      pl: "poland"
      be: "belgium"
      fr: "france"
      bg: "bulgaria"
      dk: "denmark"
      hr: "croatia"
      de: "germany"
      hu: "hungary"
      ba: "bosnia/herzegovina"
      fi: "finland"
      by: "belarus"
      fo: "faeroe islands"
      mc: "monaco"
      cy: "cyprus"
      mk: "macedonia"
      sk: "slovakia"
      mt: "maltu"
      si: "slovenia"
      sm: "san marino"
      se: "sweden"
      gb: "united kingdom"
    oceania:
      ck: "cook islands"
      cx: "christmas island"
      pw: "palau"
      tv: "tuvalu"
      ki: "kiribati"
      mh: "marshall islands"
      nu: "niue"
      to: "tonga"
      nz: "new zealand"
      au: "australia"
      vu: "vanuatu"
      sb: "solomon islands"
      ws: "samoa"
      fj: "fiji"
      fm: "micronesia"
    africa:
      gw: "guinea-bissau"
      zm: "zambia"
      ci: "ivory coast"
      eh: "western sahara"
      gq: "equatorial guinea"
      eg: "egypt"
      cg: "congo"
      cf: "central african republic"
      ao: "angola"
      ga: "gabon"
      et: "ethiopia"
      gn: "guinea"
      gm: "gambia"
      zw: "zimbabwe"
      cv: "cape verde"
      gh: "ghana"
      rw: "rwanda"
      tz: "tanzania"
      cm: "cameroon"
      na: "namibia"
      ne: "niger"
      ng: "nigeria"
      tn: "tunisia"
      lr: "liberia"
      ls: "lesotho"
      tg: "togo"
      td: "chad"
      er: "eritrea"
      ly: "libya"
      bf: "burkina faso"
      dj: "djibouti"
      sl: "sierra leone"
      bi: "burundi"
      bj: "benin"
      za: "south africa"
      bw: "botswana"
      dz: "algeria"
      sz: "swaziland"
      mg: "madagascar"
      ma: "morocco"
      ke: "kenya"
      ml: "mali"
      km: "comoros"
      st: "sao tome and principe"
      mu: "mauritius"
      mw: "malawi"
      so: "somalia"
      sn: "senegal"
      mr: "mauritania"
      sc: "seychelles"
      ug: "uganda"
      sd: "sudan"
      mz: "mozambique"
    asia:
      mn: "mongolia"
      cn: "china"
      af: "afghanistan"
      vn: "vietnam"
      ge: "georgia"
      in: "india"
      az: "azerbaijan"
      id: "indonesia"
      ru: "russia"
      la: "laos"
      tw: "taiwan"
      tr: "turkey"
      lk: "sri lanka"
      tm: "turkmenistan"
      tj: "tajikistan"
      pg: "papua new guinea"
      th: "thailand"
      np: "nepal"
      pk: "pakistan"
      ph: "philippines"
      bd: "bangladesh"
      ua: "ukraine"
      bn: "brunei"
      jp: "japan"
      bt: "bhutan"
      hk: "hong kong"
      kg: "kyrgyzstan"
      uz: "uzbekistan"
      mm: "burma (myanmar)"
      sg: "singapore"
      mo: "macau"
      kh: "cambodia"
      kr: "korea"
      mv: "maldives"
      kz: "kazakhstan"
      my: "malaysia"
    north america:
      gt: "guatemala"
      ag: "antigua and barbuda"
      vg: "british virgin islands (uk)"
      ai: "anguilla (uk)"
      vi: "virgin island"
      ca: "canada"
      gd: "grenada"
      aw: "aruba (netherlands)"
      cr: "costa rica"
      cu: "cuba"
      pr: "puerto rico (us)"
      ni: "nicaragua"
      tt: "trinidad and tobago"
      gp: "guadeloupe (france)"
      pa: "panama"
      do: "dominican republic"
      dm: "dominica"
      bb: "barbados"
      ht: "haiti"
      jm: "jamaica"
      hn: "honduras"
      bs: "bahamas, the"
      bz: "belize"
      sx: "saint kitts and nevis"
      sv: "el salvador"
      us: "united states"
      mq: "martinique (france)"
      ms: "monsterrat (uk)"
      ky: "cayman islands (uk)"
      mx: "mexico"
    south america:
      py: "paraguay"
      co: "colombia"
      ve: "venezuela"
      cl: "chile"
      sr: "suriname"
      bo: "bolivia"
      ec: "ecuador"
      gf: "french guiana"
      ar: "argentina"
      gy: "guyana"
      br: "brazil"
      pe: "peru"
      uy: "uruguay"
      fk: "falkland islands"
    middle east:
      om: "oman"
      lb: "lebanon"
      iq: "iraq"
      ye: "yemen"
      ir: "iran"
      bh: "bahrain"
      sy: "syria"
      qa: "qatar"
      jo: "jordan"
      kw: "kuwait"
      il: "israel"
      ae: "united arab emirates"
      sa: "saudi arabia"
development:
  <<: *defaults

test:
  <<: *defaults
  email: test@example.com

production:
  <<: *defaults
  email: info@example.com
  secret: 321oof

