'Accesorios Mujer':
  cod: 315
  sales_rate: 2.42
  staff_type: 2
  world: 'Mujer'
  employees:
    sellers: 0
    cashiers: 13
    sales_assistant: 12
    store_assistant: 0
    backstore_assistant: 0
    fitting_room_assistant: 0
'Administración':
  cod: 389
  sales_rate:
  staff_type:
  world: 'Administración'
  employees:
    sellers: 0
    cashiers: 0
    sales_assistant: 0
    store_assistant: 0
    backstore_assistant: 0
    fitting_room_assistant: 0
'Alfombras y Maletas':
  cod: 338
  sales_rate: 0.33
  staff_type: 3
  world: 'DecoHogar'
  employees:
    sellers: 8
    cashiers: 0
    sales_assistant: 0
    store_assistant: 0
    backstore_assistant: 0
    fitting_room_assistant: 0
'Audio y Video':
  cod: 364
  sales_rate: 13.44
  staff_type: 3
  world: 'ElectroHogar'
  employees:
    sellers: 20
    cashiers: 0
    sales_assistant: 0
    store_assistant: 0
    backstore_assistant: 0
    fitting_room_assistant: 0
'Benefit':
  cod: 320
  sales_rate:
  staff_type:
  world: 'Mujer'
  employees:
    sellers: 0
    cashiers: 0
    sales_assistant: 0
    store_assistant: 0
    backstore_assistant: 0
    fitting_room_assistant: 0
'Benetton':
  cod: 311
  sales_rate:
  staff_type:
  world: 'Mujer'
  employees:
    sellers: 0
    cashiers: 0
    sales_assistant: 0
    store_assistant: 0
    backstore_assistant: 0
    fitting_room_assistant: 0
'Blanco':
  cod: 337
  sales_rate: 2.42
  staff_type: 1
  world: 'DecoHogar'
  employees:
    sellers: 0
    cashiers: 12
    sales_assistant: 10
    store_assistant: 0
    backstore_assistant: 0
    fitting_room_assistant: 0
'Calzado Hombre':
  cod: 329
  sales_rate: 1.39
  staff_type: 3
  world: 'Hombre'
  employees:
    sellers: 10
    cashiers: 0
    sales_assistant: 0
    store_assistant: 0
    backstore_assistant: 10
    fitting_room_assistant: 0
'Calzado  Infantil':
  cod: 331
  sales_rate: 0.42
  staff_type: 3
  world: 'Niños'
  employees:
    sellers: 15
    cashiers: 0
    sales_assistant: 0
    store_assistant: 0
    backstore_assistant: 10
    fitting_room_assistant: 0
'Calzado Mujer':
  cod: 330
  sales_rate: 3.02
  staff_type: 3
  world: 'Mujer'
  employees:
    sellers: 10
    cashiers: 0
    sales_assistant: 0
    store_assistant: 0
    backstore_assistant: 10
    fitting_room_assistant: 0
'CMR puntos':
  cod: 389
  sales_rate:
  staff_type:
  world: 'Administración'
  employees:
    sellers: 0
    cashiers: 0
    sales_assistant: 0
    store_assistant: 0
    fitting_room_assistant: 0
'Colegial':
  cod: 339
  sales_rate:
  staff_type:
  world: 'Niños'
  employees:
    sellers: 0
    cashiers: 0
    sales_assistant: 0
    store_assistant: 0
    fitting_room_assistant: 0
'Computación y Hogar':
  cod: 335
  sales_rate: 9.44
  staff_type:
  world: 'ElectroHogar'
  employees:
    sellers: 56
    cashiers: 0
    sales_assistant: 0
    store_assistant: 0
    fitting_room_assistant: 0
'Confección, Camisería y Ropa Interior':
  cod: 303
  sales_rate: 1.79
  staff_type: 1
  world: 'Hombre'
  employees:
    sellers: 0
    cashiers: 10
    sales_assistant: 10
    store_assistant: 0
    fitting_room_assistant: 10
'Cortinas':
  cod: 339
  sales_rate: 0.24
  staff_type: 3
  world: 'DecoHogar'
  employees:
    sellers: 10
    cashiers: 0
    sales_assistant: 0
    store_assistant: 0
    fitting_room_assistant: 0
'Cuidado Personal':
  cod: 358
  sales_rate: 0.24
  staff_type: 3
  world: 'ElectroHogar'
  employees:
    sellers: 10
    cashiers: 0
    sales_assistant: 0
    store_assistant: 0
    fitting_room_assistant: 0
'Deportes':
  cod: 307
  sales_rate: 3.73
  staff_type: 1
  world: 'Hombre'
  employees:
    sellers: 0
    cashiers: 10
    sales_assistant: 10
    store_assistant: 0
    fitting_room_assistant: 10
'Dormitorio':
  cod: 308
  sales_rate: 2.49
  staff_type: 3
  world: 'DecoHogar'
  employees:
    sellers: 16
    cashiers: 0
    sales_assistant: 0
    store_assistant: 0
    fitting_room_assistant: 0
'Electrodomésticos':
  cod: 334
  sales_rate: 3.75
  staff_type: 3
  world: 'ElectroHogar'
  employees:
    sellers: 27
    cashiers: 0
    sales_assistant: 0
    store_assistant: 0
    fitting_room_assistant: 0
'Fotografía':
  cod: 355
  sales_rate: 0.75
  staff_type: 3
  world: 'ElectroHogar'
  employees:
    sellers: 10
    cashiers: 0
    sales_assistant: 0
    store_assistant: 0
    backstore_assistant: 10
    fitting_room_assistant: 0
'Gourmet':
  cod: 343
  sales_rate: 0.74
  staff_type: 2
  world: 'DecoHogar'
  employees:
    sellers: 0
    cashiers: 10
    sales_assistant: 0
    store_assistant: 10
    backstore_assistant: 0
    fitting_room_assistant: 0
'Juguetería':
  cod: 328
  sales_rate: 2.22
  staff_type: 2
  world: 'Niños'
  employees:
    sellers: 0
    cashiers: 10
    sales_assistant: 0
    store_assistant: 10
    backstore_assistant: 0
    fitting_room_assistant: 0
'Juvenil Hombre':
  cod: 305
  sales_rate: 3.65
  staff_type: 1
  world: 'Hombre'
  employees:
    sellers: 0
    cashiers: 10
    sales_assistant: 10
    store_assistant: 0
    fitting_room_assistant: 10
'Juvenil Mujer':
  cod: 312
  sales_rate: 3.41
  staff_type: 1
  world: 'Mujer'
  employees:
    sellers: 23
    cashiers:
    sales_assistant:
    store_assistant:
    fitting_room_assistant:
'Lencería y Corsetería':
  cod: 313
  sales_rate: 3.75
  staff_type: 3
  world: 'Mujer'
  employees:
    sellers: 23
    cashiers: 0
    sales_assistant: 0
    store_assistant: 0
    fitting_room_assistant: 0
'Línea Blanca':
  cod: 332
  sales_rate: 4.52
  staff_type:
  world: 'ElectroHogar'
  employees:
    sellers: 31
    cashiers:
    sales_assistant:
    store_assistant:
    fitting_room_assistant:
'Menaje':
  cod: 346
  sales_rate: 1.33
  staff_type: 1
  world: 'DecoHogar'
  employees:
    sellers: 0
    cashiers: 10
    sales_assistant: 10
    store_assistant: 0
    fitting_room_assistant: 0
'MNG':
  cod: 310
  sales_rate:
  staff_type:
  world: 'Mujer'
  employees:
    sellers:
    cashiers:
    sales_assistant:
    store_assistant:
    fitting_room_assistant:
'Muebles':
  cod: 340
  sales_rate: 2.55
  staff_type:
  world: 'DecoHogar'
  employees:
    sellers: 15
    cashiers:
    sales_assistant:
    store_assistant:
    fitting_room_assistant:
'Mujer':
  cod: 309
  sales_rate: 9.14
  staff_type: 1
  world: 'Mujer'
  employees:
    sellers: 0
    cashiers: 10
    sales_assistant: 10
    store_assistant: 0
    fitting_room_assistant: 10
'Niñas (2-8)':
  cod: 323
  sales_rate: 0.81
  staff_type: 1
  world: 'Niños'
  employees:
    sellers: 0
    cashiers: 10
    sales_assistant: 10
    store_assistant: 0
    fitting_room_assistant: 10
'Niños (2-8)':
  cod: 322
  sales_rate: 0.81
  staff_type: 1
  world: 'Niños'
  employees:
    sellers: 0
    cashiers: 10
    sales_assistant: 10
    store_assistant: 0
    fitting_room_assistant: 10
'Niñas (8-16)':
  cod: 325
  sales_rate: 0.81
  staff_type: 1
  world: 'Niños'
  employees:
    sellers: 0
    cashiers: 10
    sales_assistant: 10
    store_assistant: 0
    fitting_room_assistant: 10
'Niños (8-16)':
  cod: 324
  sales_rate: 0.75
  staff_type: 1
  world: 'Niños'
  employees:
    sellers: 0
    cashiers: 10
    sales_assistant: 10
    store_assistant: 0
    fitting_room_assistant: 10
'Perfumería':
  cod: 320
  sales_rate: 5.06
  staff_type: 3
  world: 'Mujer'
  employees:
    sellers: 20
    cashiers: 0
    sales_assistant: 0
    store_assistant: 0
    fitting_room_assistant: 0
'Regalería':
  cod: 342
  sales_rate: 1.14
  staff_type: 2
  world: 'DecoHogar'
  employees:
    sellers: 0
    cashiers: 10
    sales_assistant: 0
    store_assistant: 10
    fitting_room_assistant: 0
'Relojes':
  cod: 313
  sales_rate:
  staff_type:
  world: 'Mujer'
  employees:
    sellers:
    cashiers:
    sales_assistant:
    store_assistant:
    fitting_room_assistant:
'Servicios':
  cod: 389
  sales_rate:
  staff_type:
  world: 'Administración'
  employees:
    sellers:
    cashiers:
    sales_assistant:
    store_assistant:
    fitting_room_assistant:
'Sport Hombre':
  cod: 302
  sales_rate: 3.65
  staff_type: 1
  world: 'Hombre'
  employees:
    sellers: 0
    cashiers: 10
    sales_assistant: 10
    store_assistant: 0
    fitting_room_assistant: 10
'Telefonía':
  cod: 387
  sales_rate: 3.65
  staff_type:
  world: 'ElectroHogar'
  employees:
    sellers:
    cashiers:
    sales_assistant:
    store_assistant:
    fitting_room_assistant:
'Trajes de Baño':
  cod: 390
  sales_rate:
  staff_type:
  world: 'Mujer'
  employees:
    sellers:
    cashiers:
    sales_assistant:
    store_assistant:
    fitting_room_assistant:
'Vestuario Bebe, Recién Nacidos':
  cod: 326
  sales_rate: 2.52
  staff_type:
  world: 'Niños'
  employees:
    sellers: 15
    cashiers:
    sales_assistant:
    store_assistant:
    fitting_room_assistant:
'Video Juegos':
  cod: 304
  sales_rate:
  staff_type:
  world: 'ElectroHogar'
  employees:
    sellers:
    cashiers:
    sales_assistant:
    store_assistant:
    fitting_room_assistant:
'Zapatillas':
  cod: 306
  sales_rate: 2.42
  staff_type:
  world: 'Hombre'
  employees:
    sellers: 13
    cashiers:
    sales_assistant:
    store_assistant:
    fitting_room_assistant: